export const styles = {
  root: {
    fontFamily: "system-ui, -apple-system, sans-serif",
    maxWidth: 720,
    margin: "0 auto",
    padding: "2rem 1.25rem",
    color: "var(--color-text-primary, #3d3d3a)",
  },
  header: { marginBottom: "1.5rem" },
  headerInner: { marginBottom: "0.75rem" },
  headerEyebrow: {
    fontSize: 11,
    fontFamily: "monospace",
    letterSpacing: "0.12em",
    textTransform: "uppercase",
    color: "var(--color-text-secondary, #73726c)",
    display: "block",
    marginBottom: 4,
  },
  headerTitle: {
    fontSize: 24,
    fontWeight: 600,
    margin: "0 0 6px",
    color: "var(--color-text-primary, #3d3d3a)",
    letterSpacing: "-0.01em",
  },
  headerSub: {
    fontSize: 14,
    color: "var(--color-text-secondary, #73726c)",
    lineHeight: 1.65,
    margin: 0,
  },
  stringBadges: { display: "flex", flexWrap: "wrap", gap: 6 },
  badge: {
    fontSize: 12,
    padding: "3px 10px",
    borderRadius: 20,
    background: "var(--color-background-secondary, #f5f4f0)",
    border: "0.5px solid var(--color-border-tertiary, rgba(61,61,58,0.15))",
    color: "var(--color-text-secondary, #73726c)",
    fontFamily: "monospace",
  },
  tabRow: {
    display: "flex",
    gap: 6,
    marginBottom: "1.25rem",
    borderBottom: "0.5px solid var(--color-border-tertiary, rgba(61,61,58,0.15))",
    paddingBottom: "0",
  },
  tabBtn: {
    padding: "8px 16px",
    borderRadius: "8px 8px 0 0",
    border: "0.5px solid transparent",
    background: "transparent",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 500,
    color: "var(--color-text-secondary, #73726c)",
    marginBottom: -1,
    transition: "all 0.12s",
  },
  tabBtnActive: {
    background: "var(--color-background-primary, #fff)",
    border: "0.5px solid var(--color-border-tertiary, rgba(61,61,58,0.15))",
    borderBottomColor: "var(--color-background-primary, #fff)",
    color: "var(--color-text-primary, #3d3d3a)",
    fontWeight: 600,
  },
  grid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(148px, 1fr))",
    gap: 8,
    marginBottom: "1.25rem",
  },
  techBtn: {
    padding: "10px 10px 8px",
    borderRadius: 8,
    border: "0.5px solid var(--color-border-secondary, rgba(61,61,58,0.3))",
    background: "var(--color-background-primary, #fff)",
    cursor: "pointer",
    textAlign: "left",
    transition: "all 0.12s",
    display: "flex",
    flexDirection: "column",
    gap: 2,
  },
  techBtnActive: { borderWidth: 1.5 },
  techSymbol: {
    fontFamily: "monospace",
    fontSize: 15,
    fontWeight: 700,
    display: "block",
    marginBottom: 2,
  },
  techName: {
    fontSize: 12,
    fontWeight: 600,
    color: "var(--color-text-primary, #3d3d3a)",
    display: "block",
  },
  techShort: {
    fontSize: 11,
    color: "var(--color-text-secondary, #73726c)",
    display: "block",
  },
  panel: {
    border: "0.5px solid var(--color-border-tertiary, rgba(61,61,58,0.15))",
    borderRadius: 12,
    background: "var(--color-background-primary, #fff)",
    overflow: "hidden",
  },
  panelHeader: {
    padding: "1rem 1.25rem",
    borderBottom: "0.5px solid var(--color-border-tertiary, rgba(61,61,58,0.15))",
    display: "flex",
    alignItems: "center",
    gap: 14,
  },
  panelSymbol: {
    fontFamily: "monospace",
    fontSize: 22,
    fontWeight: 700,
    minWidth: 64,
  },
  panelTitle: {
    fontSize: 16,
    fontWeight: 600,
    color: "var(--color-text-primary, #3d3d3a)",
  },
  panelShort: {
    fontSize: 13,
    color: "var(--color-text-secondary, #73726c)",
    marginTop: 2,
  },
  goCheckBtn: {
    marginLeft: "auto",
    padding: "5px 12px",
    borderRadius: 8,
    border: "0.5px solid var(--color-border-secondary, rgba(61,61,58,0.3))",
    background: "var(--color-background-secondary, #f5f4f0)",
    cursor: "pointer",
    fontSize: 12,
    fontWeight: 500,
    color: "var(--color-text-secondary, #73726c)",
    whiteSpace: "nowrap",
  },
  canvasWrap: {
    background: "var(--color-background-secondary, #f5f4f0)",
    padding: "0.75rem 1rem",
    borderBottom: "0.5px solid var(--color-border-tertiary, rgba(61,61,58,0.15))",
  },
  playbackRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "0.75rem 1.25rem",
    borderBottom: "0.5px solid var(--color-border-tertiary, rgba(61,61,58,0.15))",
  },
  playBtn: {
    padding: "6px 14px",
    borderRadius: 8,
    border: "0.5px solid var(--color-border-secondary, rgba(61,61,58,0.3))",
    background: "var(--color-background-primary, #fff)",
    cursor: "pointer",
    fontSize: 13,
    fontWeight: 600,
    color: "var(--color-text-primary, #3d3d3a)",
    whiteSpace: "nowrap",
  },
  playBtnActive: {},
  progressTrack: {
    flex: 1,
    height: 4,
    background: "var(--color-background-secondary, #f5f4f0)",
    borderRadius: 2,
    overflow: "hidden",
  },
  progressFill: { height: "100%", borderRadius: 2, transition: "width 0.04s linear" },
  explanation: {
    fontSize: 14,
    color: "var(--color-text-secondary, #73726c)",
    lineHeight: 1.7,
    padding: "1rem 1.25rem 0.75rem",
    margin: 0,
  },
  tipBox: {
    margin: "0 1.25rem 1.25rem",
    borderLeft: "2.5px solid",
    borderRadius: "0 8px 8px 0",
    padding: "0.75rem 1rem",
    display: "flex",
    flexDirection: "column",
    gap: 4,
  },
  tipLabel: {
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.08em",
    fontFamily: "monospace",
  },
  tipText: {
    fontSize: 13,
    color: "var(--color-text-primary, #3d3d3a)",
    lineHeight: 1.6,
  },
}
