export const trackerStyles = {
  tracker: {
    border: "0.5px solid var(--color-border-tertiary, rgba(61,61,58,0.15))",
    borderRadius: 12,
    background: "var(--color-background-primary, #fff)",
    overflow: "hidden",
  },
  trackerHeader: {
    padding: "1rem 1.25rem",
    borderBottom: "0.5px solid var(--color-border-tertiary, rgba(61,61,58,0.15))",
    display: "flex",
    justifyContent: "space-between",
    alignItems: "flex-start",
    gap: 12,
  },
  trackerTitle: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    fontSize: 15,
    fontWeight: 600,
    color: "var(--color-text-primary, #3d3d3a)",
    marginBottom: 4,
  },
  trackerDate: {
    fontSize: 12,
    fontWeight: 400,
    color: "var(--color-text-secondary, #73726c)",
  },
  trackerMsg: { fontSize: 13, fontWeight: 500 },
  trackerActions: { display: "flex", gap: 6, flexShrink: 0 },
  ghostBtn: {
    padding: "4px 10px",
    borderRadius: 6,
    border: "0.5px solid var(--color-border-secondary, rgba(61,61,58,0.3))",
    background: "transparent",
    cursor: "pointer",
    fontSize: 12,
    color: "var(--color-text-secondary, #73726c)",
  },
  progressWrap: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "0.65rem 1.25rem",
    borderBottom: "0.5px solid var(--color-border-tertiary, rgba(61,61,58,0.15))",
  },
  progressBar: {
    flex: 1,
    height: 6,
    background: "var(--color-background-secondary, #f5f4f0)",
    borderRadius: 3,
    overflow: "hidden",
  },
  progressBarFill: { height: "100%", borderRadius: 3, transition: "width 0.3s ease" },
  progressLabel: {
    fontSize: 12,
    fontWeight: 600,
    fontFamily: "monospace",
    color: "var(--color-text-secondary, #73726c)",
    whiteSpace: "nowrap",
  },
  historyPanel: {
    padding: "0.75rem 1.25rem",
    borderBottom: "0.5px solid var(--color-border-tertiary, rgba(61,61,58,0.15))",
    background: "var(--color-background-secondary, #f5f4f0)",
  },
  historyTitle: {
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.1em",
    fontFamily: "monospace",
    color: "var(--color-text-secondary, #73726c)",
    marginBottom: 8,
  },
  historyRow: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    marginBottom: 6,
  },
  historyDate: {
    fontSize: 12,
    color: "var(--color-text-secondary, #73726c)",
    minWidth: 100,
  },
  historyBar: {
    flex: 1,
    height: 4,
    background: "var(--color-background-tertiary, #e8e7e3)",
    borderRadius: 2,
    overflow: "hidden",
  },
  historyBarFill: {
    height: "100%",
    borderRadius: 2,
    background: "linear-gradient(90deg, #378ADD, #534AB7)",
  },
  historyCount: {
    fontSize: 11,
    fontFamily: "monospace",
    color: "var(--color-text-secondary, #73726c)",
    minWidth: 32,
    textAlign: "right",
  },
  historyEmpty: {
    padding: "0.75rem 1.25rem",
    fontSize: 13,
    color: "var(--color-text-secondary, #73726c)",
  },
  checkGrid: {
    display: "grid",
    gridTemplateColumns: "repeat(auto-fill, minmax(200px, 1fr))",
    gap: 0,
  },
  checkItem: {
    display: "flex",
    alignItems: "center",
    gap: 10,
    padding: "0.7rem 1.1rem",
    borderBottom: "0.5px solid var(--color-border-tertiary, rgba(61,61,58,0.1))",
    borderLeft: "2px solid transparent",
    transition: "all 0.15s",
  },
  checkItemDone: {},
  checkbox: {
    width: 20,
    height: 20,
    borderRadius: 5,
    border: "1.5px solid",
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    cursor: "pointer",
    flexShrink: 0,
    transition: "all 0.15s",
  },
  checkLabel: {
    display: "flex",
    flexDirection: "column",
    gap: 1,
    background: "none",
    border: "none",
    cursor: "pointer",
    textAlign: "left",
    padding: 0,
    flex: 1,
  },
  checkSymbol: {
    fontFamily: "monospace",
    fontSize: 12,
    fontWeight: 700,
  },
  checkName: {
    fontSize: 12,
    fontWeight: 500,
    color: "var(--color-text-primary, #3d3d3a)",
    lineHeight: 1.3,
    transition: "opacity 0.15s",
  },
}
